export type TranslationLanguage = "en" | "sw" | "fr" | "rw";

export const LANGUAGE_STORAGE_KEY = "facegrem_language";

export const languageLabels: Record<TranslationLanguage, string> = {
  en: "English",
  sw: "Swahili",
  fr: "French",
  rw: "Kinyarwanda",
};

export const supportedLanguages: TranslationLanguage[] = ["en", "sw", "fr", "rw"];

export const isTranslationLanguage = (
  value: string | null | undefined
): value is TranslationLanguage => {
  return value === "en" || value === "sw" || value === "fr" || value === "rw";
};

export const getStoredLanguage = (): TranslationLanguage => {
  if (typeof window === "undefined") return "en";

  const storedLanguage = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return isTranslationLanguage(storedLanguage) ? storedLanguage : "en";
};

export const saveStoredLanguage = (language: TranslationLanguage) => {
  if (typeof window === "undefined") return;

  window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
  window.dispatchEvent(
    new CustomEvent("facegrem-language-change", {
      detail: { language },
    })
  );
};

export const uiTranslations = {
  en: {
    loading: "Loading...",
    loadingFeed: "Loading FaceGrem feed...",
    loadingMessages: "Loading messages...",
    loadingProfile: "Loading profile...",
    loadingVideos: "Loading videos...",
    loadingCommunities: "Loading communities...",
    loadingGroups: "Loading groups...",
    loadingNotifications: "Loading notifications...",
    loadingSaved: "Loading saved posts...",

    brandName: "FaceGrem",
    brandTagline: "Your social world, live now",
    videoWorld: "Video world",
    messagesTagline: "Messages",
    groupsTagline: "Groups",
    communitiesTagline: "Communities",
    profileTagline: "Profile",

    navigation: "Navigation",
    more: "More",
    homeFeed: "Home Feed",
    feed: "Feed",
    videos: "Videos",
    communities: "Communities",
    community: "Community",
    groups: "Groups",
    messages: "Messages",
    chat: "Chat",
    saved: "Saved",
    savedPosts: "Saved Posts",
    profile: "Profile",
    notifications: "Notifications",
    settings: "Settings",
    language: "Language",
    privacy: "Privacy",
    help: "Help",
    logout: "Log out",
    signingOut: "Signing out...",
    search: "Search",
    searchPlaceholder: "Search posts, creators, communities, topics...",
    searchConversations: "Search conversations...",
    searchVideos: "Search videos, creators, categories...",
    searchCommunities: "Search communities, topics, categories...",
    searchGroups: "Search groups, topics, categories...",
    searchPeople: "Search people",

    welcomeBack: "Welcome back",
    goodToSeeYou: "Good to see you",
    discoverText:
      "Discover what people are sharing right now across FaceGrem — moments, ideas, videos, conversations, and communities.",
    create: "Create",
    close: "Close",
    clear: "Clear",
    post: "Post",
    posting: "Posting...",
    createPost: "Create post",
    createPostSubtitle: "Share a thought, photo, story, or video with FaceGrem",
    whatsOnMind: "What’s on your mind today?",
    publicPost: "Public post",
    liveComposer: "Live composer",
    public: "Public",
    delete: "Delete",
    viewDiscussion: "View discussion",
    like: "Like",
    liked: "Liked",
    translate: "Translate",
    translating: "Translating...",
    translateShowOriginal: "Show original",
    translatedTo: "Translated to",
    noPosts: "No posts found here yet.",
    tryAnotherTab: "Try another feed tab or create the first post.",

    stories: "Stories",
    story: "Story",
    createStory: "Create story",
    useCreateStory: "Use Create story to share quick moments.",
    addVisual: "Add a photo or video to make your post stand out.",
    storiesSubtitle: "Quick moments from people around you",
    shareQuickMoment: "Share a quick moment",
    yourStory: "Your story",
    storyImage: "Story image",
    uploading: "Uploading...",
    uploadingStory: "Uploading story...",
    chooseStoryImage: "Choose story image",

    photo: "Photo",
    video: "Video",
    live: "Live",
    photoUpload: "Photo upload",
    videoLink: "Video link",
    liveStreamLink: "Live stream link",
    pasteVideoHelp: "Paste a YouTube link or direct video URL",
    textBadge: "Text",
    imageAttached: "Image attached",
    videoLinked: "Video linked",

    yourCommunities: "Your communities",
    viewAll: "View all",
    joinCommunitiesText: "Join communities to keep your favorite spaces close.",
    communityFallback: "Community",
    createCommunity: "Create community",
    join: "Join",
    leave: "Leave",
    members: "Members",

    createGroup: "Create group",
    groupBuilder: "Group builder",
    groupName: "Group name",
    categoryOptional: "Category (optional)",
    groupDescription: "Describe your group",
    creating: "Creating...",
    joined: "Joined",
    all: "All",
    posts: "Posts",
    groupFallback: "Group",
    noGroups: "No groups found here yet.",
    noGroupsSub: "Try a different search or create the first group.",

    privateChats: "Private chats",
    chats: "Chats",
    focus: "Focus",
    open: "Open",
    idle: "Idle",
    peopleToMessage: "People to message",
    peopleEmpty: "Start chatting with people from their profile pages.",
    conversations: "Conversations",
    activeChats: "active chats",
    noConversations: "No conversations yet.",
    openConversation: "Open conversation",
    selectConversation: "Select a conversation",
    selectConversationHelp:
      "Open a chat from the left to read messages and start the conversation.",
    openProfile: "Open profile",
    member: "member",
    noMessages: "No messages yet. Start the conversation.",
    message: "Message",
    writeFirst: "Write a message first.",
    selectFirst: "Select a conversation first.",
    sending: "Sending...",
    send: "Send",
    audioCall: "Audio call",
    videoCall: "Video call",
    endCall: "End call",
    callPreview: "Call preview",
    callPermission: "Allow microphone/camera permission to start the preview.",
    incomingAudioCall: "Incoming audio call",
    incomingVideoCall: "Incoming video call",
    isCallingYou: "is calling you",
    accept: "Accept",
    decline: "Decline",
    callDeclined: "Call declined",
    callStarted: "Call started",
    connecting: "Connecting...",
    connected: "Connected",
    online: "online",
    remoteVideo: "Remote video",
    localPreview: "Your preview",
    callEnded: "Call ended",
    callFailed: "Call failed",
    voiceRecord: "Voice",
    recording: "Recording...",
    stop: "Stop",
    voiceMessage: "Voice message",
    voiceUploadError: "Could not send voice message.",
    recordingTip:
      "Speak clearly near your microphone. Use your browser or system mic settings if your voice is not captured.",
    micActive: "Microphone active",

    creatorDashboard: "Creator dashboard",
    tabs: "Tabs",
    creators: "Creators",
    creator: "creator",
    creatorSpotlight: "Creator spotlight",
    trendingCreators: "Trending creators",
    watchNow: "Watch now",
    upload: "Upload",
    uploadVideo: "Upload video",
    publishVideo: "Publish video",
    videoTitle: "Video title",
    videoDescription: "Video description",
    noVideos: "No videos found here yet.",
    noVideosSub: "Try another tab or upload the first video.",
    views: "views",

    quickDetails: "Tap to view quick details",
    savedStat: "Saved",
    alertsStat: "Alerts",
    groupsStat: "Groups",
    openProfileTitle: "Open Profile",
  },

  sw: {
    loading: "Inapakia...",
    loadingFeed: "Inapakia FaceGrem...",
    loadingMessages: "Inapakia ujumbe...",
    loadingProfile: "Inapakia wasifu...",
    loadingVideos: "Inapakia video...",
    loadingCommunities: "Inapakia jumuiya...",
    loadingGroups: "Inapakia makundi...",
    loadingNotifications: "Inapakia arifa...",
    loadingSaved: "Inapakia machapisho yaliyohifadhiwa...",

    brandName: "FaceGrem",
    brandTagline: "Dunia yako ya kijamii, moja kwa moja sasa",
    videoWorld: "Dunia ya video",
    messagesTagline: "Ujumbe",
    groupsTagline: "Makundi",
    communitiesTagline: "Jumuiya",
    profileTagline: "Wasifu",

    navigation: "Urambazaji",
    more: "Zaidi",
    homeFeed: "Mkondo Mkuu",
    feed: "Feed",
    videos: "Video",
    communities: "Jumuiya",
    community: "Jumuiya",
    groups: "Makundi",
    messages: "Ujumbe",
    chat: "Chat",
    saved: "Vilivyohifadhiwa",
    savedPosts: "Machapisho yaliyohifadhiwa",
    profile: "Wasifu",
    notifications: "Arifa",
    settings: "Mipangilio",
    language: "Lugha",
    privacy: "Faragha",
    help: "Msaada",
    logout: "Toka",
    signingOut: "Inatoka...",
    search: "Tafuta",
    searchPlaceholder: "Tafuta machapisho, wabunifu, jumuiya, mada...",
    searchConversations: "Tafuta mazungumzo...",
    searchVideos: "Tafuta video, wabunifu, makundi...",
    searchCommunities: "Tafuta jumuiya, mada, makundi...",
    searchGroups: "Tafuta makundi, mada, kategoria...",
    searchPeople: "Tafuta watu",

    welcomeBack: "Karibu tena",
    goodToSeeYou: "Vizuri kukuona",
    discoverText:
      "Gundua watu wanashiriki nini sasa hivi kwenye FaceGrem — matukio, mawazo, video, mazungumzo, na jumuiya.",
    create: "Tengeneza",
    close: "Funga",
    clear: "Futa",
    post: "Chapisha",
    posting: "Inachapisha...",
    createPost: "Tengeneza chapisho",
    createPostSubtitle: "Shiriki wazo, picha, hadithi, au video kwenye FaceGrem",
    whatsOnMind: "Unafikiria nini leo?",
    publicPost: "Chapisho la umma",
    liveComposer: "Muundaji wa moja kwa moja",
    public: "Umma",
    delete: "Futa",
    viewDiscussion: "Tazama mjadala",
    like: "Penda",
    liked: "Umeipenda",
    translate: "Tafsiri",
    translating: "Inatafsiri...",
    translateShowOriginal: "Onyesha asili",
    translatedTo: "Imetafsiriwa kwa",
    noPosts: "Hakuna machapisho hapa bado.",
    tryAnotherTab: "Jaribu kichupo kingine au tengeneza chapisho la kwanza.",

    stories: "Hadithi",
    story: "Hadithi",
    createStory: "Tengeneza hadithi",
    useCreateStory: "Tumia Tengeneza hadithi kushiriki matukio ya haraka.",
    addVisual: "Ongeza picha au video ili chapisho lako lionekane zaidi.",
    storiesSubtitle: "Matukio ya haraka kutoka kwa watu walio karibu nawe",
    shareQuickMoment: "Shiriki tukio la haraka",
    yourStory: "Hadithi yako",
    storyImage: "Picha ya hadithi",
    uploading: "Inapakia...",
    uploadingStory: "Inapakia hadithi...",
    chooseStoryImage: "Chagua picha ya hadithi",

    photo: "Picha",
    video: "Video",
    live: "Mubashara",
    photoUpload: "Pakia picha",
    videoLink: "Kiungo cha video",
    liveStreamLink: "Kiungo cha mubashara",
    pasteVideoHelp: "Bandika kiungo cha YouTube au video ya moja kwa moja",
    textBadge: "Maandishi",
    imageAttached: "Picha imeambatishwa",
    videoLinked: "Video imeunganishwa",

    yourCommunities: "Jumuiya zako",
    viewAll: "Tazama zote",
    joinCommunitiesText: "Jiunge na jumuiya ili kuyaweka maeneo unayopenda karibu.",
    communityFallback: "Jumuiya",
    createCommunity: "Tengeneza jumuiya",
    join: "Jiunge",
    leave: "Ondoka",
    members: "Wanachama",

    createGroup: "Tengeneza kundi",
    groupBuilder: "Mtengenezaji wa kundi",
    groupName: "Jina la kundi",
    categoryOptional: "Kategoria (si lazima)",
    groupDescription: "Eleza kundi lako",
    creating: "Inatengeneza...",
    joined: "Umejiunga",
    all: "Yote",
    posts: "Machapisho",
    groupFallback: "Kundi",
    noGroups: "Hakuna makundi hapa bado.",
    noGroupsSub: "Jaribu utafutaji mwingine au tengeneza kundi la kwanza.",

    privateChats: "Mazungumzo binafsi",
    chats: "Mazungumzo",
    focus: "Umakini",
    open: "Imefunguliwa",
    idle: "Kimya",
    peopleToMessage: "Watu wa kuwatumia ujumbe",
    peopleEmpty: "Anza kuzungumza na watu kutoka kwenye ukurasa wao wa wasifu.",
    conversations: "Mazungumzo",
    activeChats: "mazungumzo hai",
    noConversations: "Hakuna mazungumzo bado.",
    openConversation: "Fungua mazungumzo",
    selectConversation: "Chagua mazungumzo",
    selectConversationHelp:
      "Fungua chat upande wa kushoto kusoma ujumbe na kuanza mazungumzo.",
    openProfile: "Fungua wasifu",
    member: "mwanachama",
    noMessages: "Hakuna ujumbe bado. Anza mazungumzo.",
    message: "Ujumbe",
    writeFirst: "Andika ujumbe kwanza.",
    selectFirst: "Chagua mazungumzo kwanza.",
    sending: "Inatuma...",
    send: "Tuma",
    audioCall: "Simu ya sauti",
    videoCall: "Simu ya video",
    endCall: "Maliza simu",
    callPreview: "Muonekano wa simu",
    callPermission: "Ruhusu kipaza sauti/kamera ili kuanza muonekano.",
    incomingAudioCall: "Simu ya sauti inaingia",
    incomingVideoCall: "Simu ya video inaingia",
    isCallingYou: "anakupigia",
    accept: "Kubali",
    decline: "Kataa",
    callDeclined: "Simu imekataliwa",
    callStarted: "Simu imeanza",
    connecting: "Inaunganisha...",
    connected: "Imeunganishwa",
    online: "mtandaoni",
    remoteVideo: "Video ya upande mwingine",
    localPreview: "Muonekano wako",
    callEnded: "Simu imeisha",
    callFailed: "Simu imeshindikana",
    voiceRecord: "Sauti",
    recording: "Inarekodi...",
    stop: "Simamisha",
    voiceMessage: "Ujumbe wa sauti",
    voiceUploadError: "Imeshindikana kutuma ujumbe wa sauti.",
    recordingTip:
      "Ongea karibu na kipaza sauti. Tumia mipangilio ya mic ya browser au mfumo kama sauti yako haishikwi.",
    micActive: "Kipaza sauti kinafanya kazi",

    creatorDashboard: "Dashibodi ya mbunifu",
    tabs: "Vichupo",
    creators: "Wabunifu",
    creator: "mbunifu",
    creatorSpotlight: "Mbunifu maalum",
    trendingCreators: "Wabunifu maarufu",
    watchNow: "Tazama sasa",
    upload: "Pakia",
    uploadVideo: "Pakia video",
    publishVideo: "Chapisha video",
    videoTitle: "Kichwa cha video",
    videoDescription: "Maelezo ya video",
    noVideos: "Hakuna video hapa bado.",
    noVideosSub: "Jaribu kichupo kingine au pakia video ya kwanza.",
    views: "watazamaji",

    quickDetails: "Gusa kuona maelezo ya haraka",
    savedStat: "Hifadhi",
    alertsStat: "Arifa",
    groupsStat: "Makundi",
    openProfileTitle: "Fungua Wasifu",
  },

  fr: {
    loading: "Chargement...",
    loadingFeed: "Chargement de FaceGrem...",
    loadingMessages: "Chargement des messages...",
    loadingProfile: "Chargement du profil...",
    loadingVideos: "Chargement des vidéos...",
    loadingCommunities: "Chargement des communautés...",
    loadingGroups: "Chargement des groupes...",
    loadingNotifications: "Chargement des notifications...",
    loadingSaved: "Chargement des publications enregistrées...",

    brandName: "FaceGrem",
    brandTagline: "Votre univers social, en direct",
    videoWorld: "Univers vidéo",
    messagesTagline: "Messages",
    groupsTagline: "Groupes",
    communitiesTagline: "Communautés",
    profileTagline: "Profil",

    navigation: "Navigation",
    more: "Plus",
    homeFeed: "Fil d’accueil",
    feed: "Fil",
    videos: "Vidéos",
    communities: "Communautés",
    community: "Communauté",
    groups: "Groupes",
    messages: "Messages",
    chat: "Chat",
    saved: "Enregistrés",
    savedPosts: "Publications enregistrées",
    profile: "Profil",
    notifications: "Notifications",
    settings: "Paramètres",
    language: "Langue",
    privacy: "Confidentialité",
    help: "Aide",
    logout: "Se déconnecter",
    signingOut: "Déconnexion...",
    search: "Rechercher",
    searchPlaceholder: "Rechercher des publications, créateurs, communautés, sujets...",
    searchConversations: "Rechercher des conversations...",
    searchVideos: "Rechercher des vidéos, créateurs, catégories...",
    searchCommunities: "Rechercher des communautés, sujets, catégories...",
    searchGroups: "Rechercher des groupes, sujets, catégories...",
    searchPeople: "Rechercher des personnes",

    welcomeBack: "Bon retour",
    goodToSeeYou: "Heureux de vous revoir",
    discoverText:
      "Découvrez ce que les gens partagent en ce moment sur FaceGrem — moments, idées, vidéos, conversations et communautés.",
    create: "Créer",
    close: "Fermer",
    clear: "Effacer",
    post: "Publier",
    posting: "Publication...",
    createPost: "Créer une publication",
    createPostSubtitle: "Partagez une pensée, une photo, une story ou une vidéo sur FaceGrem",
    whatsOnMind: "À quoi pensez-vous aujourd’hui ?",
    publicPost: "Publication publique",
    liveComposer: "Éditeur en direct",
    public: "Public",
    delete: "Supprimer",
    viewDiscussion: "Voir la discussion",
    like: "J’aime",
    liked: "Aimé",
    translate: "Traduire",
    translating: "Traduction...",
    translateShowOriginal: "Afficher l’original",
    translatedTo: "Traduit en",
    noPosts: "Aucune publication ici pour le moment.",
    tryAnotherTab: "Essayez un autre onglet ou créez la première publication.",

    stories: "Stories",
    story: "Story",
    createStory: "Créer une story",
    useCreateStory: "Utilisez Créer une story pour partager des moments rapides.",
    addVisual: "Ajoutez une photo ou une vidéo pour rendre votre publication plus visible.",
    storiesSubtitle: "Moments rapides des personnes autour de vous",
    shareQuickMoment: "Partagez un moment rapide",
    yourStory: "Votre story",
    storyImage: "Image de story",
    uploading: "Téléchargement...",
    uploadingStory: "Téléchargement de la story...",
    chooseStoryImage: "Choisir l’image de la story",

    photo: "Photo",
    video: "Vidéo",
    live: "Direct",
    photoUpload: "Téléverser une photo",
    videoLink: "Lien vidéo",
    liveStreamLink: "Lien de diffusion en direct",
    pasteVideoHelp: "Collez un lien YouTube ou une URL vidéo directe",
    textBadge: "Texte",
    imageAttached: "Image jointe",
    videoLinked: "Vidéo liée",

    yourCommunities: "Vos communautés",
    viewAll: "Voir tout",
    joinCommunitiesText: "Rejoignez des communautés pour garder vos espaces préférés proches.",
    communityFallback: "Communauté",
    createCommunity: "Créer une communauté",
    join: "Rejoindre",
    leave: "Quitter",
    members: "Membres",

    createGroup: "Créer un groupe",
    groupBuilder: "Créateur de groupe",
    groupName: "Nom du groupe",
    categoryOptional: "Catégorie (facultatif)",
    groupDescription: "Décrivez votre groupe",
    creating: "Création...",
    joined: "Rejoint",
    all: "Tout",
    posts: "Publications",
    groupFallback: "Groupe",
    noGroups: "Aucun groupe trouvé pour le moment.",
    noGroupsSub: "Essayez une autre recherche ou créez le premier groupe.",

    privateChats: "Chats privés",
    chats: "Chats",
    focus: "Focus",
    open: "Ouvert",
    idle: "Inactif",
    peopleToMessage: "Personnes à contacter",
    peopleEmpty: "Commencez à discuter avec des personnes depuis leur profil.",
    conversations: "Conversations",
    activeChats: "chats actifs",
    noConversations: "Aucune conversation pour le moment.",
    openConversation: "Ouvrir la conversation",
    selectConversation: "Sélectionnez une conversation",
    selectConversationHelp:
      "Ouvrez un chat à gauche pour lire les messages et commencer la conversation.",
    openProfile: "Ouvrir le profil",
    member: "membre",
    noMessages: "Aucun message pour le moment. Commencez la conversation.",
    message: "Message",
    writeFirst: "Écrivez d’abord un message.",
    selectFirst: "Sélectionnez d’abord une conversation.",
    sending: "Envoi...",
    send: "Envoyer",
    audioCall: "Appel audio",
    videoCall: "Appel vidéo",
    endCall: "Terminer l’appel",
    callPreview: "Aperçu de l’appel",
    callPermission: "Autorisez le micro/la caméra pour démarrer l’aperçu.",
    incomingAudioCall: "Appel audio entrant",
    incomingVideoCall: "Appel vidéo entrant",
    isCallingYou: "vous appelle",
    accept: "Accepter",
    decline: "Refuser",
    callDeclined: "Appel refusé",
    callStarted: "Appel commencé",
    connecting: "Connexion...",
    connected: "Connecté",
    online: "en ligne",
    remoteVideo: "Vidéo distante",
    localPreview: "Votre aperçu",
    callEnded: "Appel terminé",
    callFailed: "Appel échoué",
    voiceRecord: "Voix",
    recording: "Enregistrement...",
    stop: "Arrêter",
    voiceMessage: "Message vocal",
    voiceUploadError: "Impossible d’envoyer le message vocal.",
    recordingTip:
      "Parlez clairement près du micro. Vérifiez le micro du navigateur ou du système si votre voix n’est pas capturée.",
    micActive: "Micro actif",

    creatorDashboard: "Tableau créateur",
    tabs: "Onglets",
    creators: "Créateurs",
    creator: "créateur",
    creatorSpotlight: "Créateur à découvrir",
    trendingCreators: "Créateurs tendance",
    watchNow: "Regarder maintenant",
    upload: "Téléverser",
    uploadVideo: "Téléverser une vidéo",
    publishVideo: "Publier la vidéo",
    videoTitle: "Titre de la vidéo",
    videoDescription: "Description de la vidéo",
    noVideos: "Aucune vidéo trouvée pour le moment.",
    noVideosSub: "Essayez un autre onglet ou téléversez la première vidéo.",
    views: "vues",

    quickDetails: "Touchez pour voir des détails rapides",
    savedStat: "Enregistré",
    alertsStat: "Alertes",
    groupsStat: "Groupes",
    openProfileTitle: "Ouvrir le profil",
  },

  rw: {
    loading: "Birimo gufunguka...",
    loadingFeed: "FaceGrem iri gufungura...",
    loadingMessages: "Ubutumwa burimo gufunguka...",
    loadingProfile: "Umwirondoro urimo gufunguka...",
    loadingVideos: "Amashusho arimo gufunguka...",
    loadingCommunities: "Imiryango irimo gufunguka...",
    loadingGroups: "Amatsinda arimo gufunguka...",
    loadingNotifications: "Amamenyesha arimo gufunguka...",
    loadingSaved: "Ibyabitswe birimo gufunguka...",

    brandName: "FaceGrem",
    brandTagline: "Isi yawe y’imbuga nkoranyambaga, aka kanya",
    videoWorld: "Isi y’amashusho",
    messagesTagline: "Ubutumwa",
    groupsTagline: "Amatsinda",
    communitiesTagline: "Imiryango",
    profileTagline: "Umwirondoro",

    navigation: "Igenzura",
    more: "Ibindi",
    homeFeed: "Urupapuro nyamukuru",
    feed: "Feed",
    videos: "Amashusho",
    communities: "Imiryango",
    community: "Umuryango",
    groups: "Amatsinda",
    messages: "Ubutumwa",
    chat: "Chat",
    saved: "Byabitswe",
    savedPosts: "Ibyanditswe byabitswe",
    profile: "Umwirondoro",
    notifications: "Amamenyesha",
    settings: "Igenamiterere",
    language: "Ururimi",
    privacy: "Ubwirinzi bwite",
    help: "Ubufasha",
    logout: "Sohoka",
    signingOut: "Birimo gusohoka...",
    search: "Shakisha",
    searchPlaceholder: "Shakisha inyandiko, abahanzi, imiryango, insanganyamatsiko...",
    searchConversations: "Shakisha ibiganiro...",
    searchVideos: "Shakisha amashusho, abahanzi, ibyiciro...",
    searchCommunities: "Shakisha imiryango, insanganyamatsiko, ibyiciro...",
    searchGroups: "Shakisha amatsinda, insanganyamatsiko, ibyiciro...",
    searchPeople: "Shakisha abantu",

    welcomeBack: "Murakaza neza nanone",
    goodToSeeYou: "Byiza kongera kukubona",
    discoverText:
      "Reba ibyo abantu basangiza ubu kuri FaceGrem — ibihe, ibitekerezo, amashusho, ibiganiro n’imiryango.",
    create: "Kora",
    close: "Funga",
    clear: "Siba",
    post: "Tangaza",
    posting: "Birimo gutangazwa...",
    createPost: "Kora inyandiko",
    createPostSubtitle: "Sangiza igitekerezo, ifoto, inkuru cyangwa amashusho kuri FaceGrem",
    whatsOnMind: "Uri gutekereza iki uyu munsi?",
    publicPost: "Inyandiko ya bose",
    liveComposer: "Gukora aka kanya",
    public: "Rubanda",
    delete: "Siba",
    viewDiscussion: "Reba ikiganiro",
    like: "Kunda",
    liked: "Wakunze",
    translate: "Hindura",
    translating: "Birimo guhindurwa...",
    translateShowOriginal: "Erekana umwimerere",
    translatedTo: "Byahinduwe mu",
    noPosts: "Nta nyandiko zirimo hano ubu.",
    tryAnotherTab: "Gerageza indi tab cyangwa ukore inyandiko ya mbere.",

    stories: "Inkuru",
    story: "Inkuru",
    createStory: "Kora inkuru",
    useCreateStory: "Koresha Kora inkuru kugira ngo usangize ibihe byihuse.",
    addVisual: "Ongeraho ifoto cyangwa video kugira ngo inyandiko yawe igaragare neza.",
    storiesSubtitle: "Ibihe byihuse by’abantu bakwegereye",
    shareQuickMoment: "Sangiza akanya kihuse",
    yourStory: "Inkuru yawe",
    storyImage: "Ifoto y’inkuru",
    uploading: "Birimo koherezwa...",
    uploadingStory: "Inkuru irimo koherezwa...",
    chooseStoryImage: "Hitamo ifoto y’inkuru",

    photo: "Ifoto",
    video: "Video",
    live: "Live",
    photoUpload: "Ohereza ifoto",
    videoLink: "Ihuza ry’amashusho",
    liveStreamLink: "Ihuza rya live",
    pasteVideoHelp: "Shyiramo link ya YouTube cyangwa video y’umwimerere",
    textBadge: "Inyandiko",
    imageAttached: "Ifoto yometseho",
    videoLinked: "Video yometseho",

    yourCommunities: "Imiryango yawe",
    viewAll: "Reba byose",
    joinCommunitiesText: "Injira mu miryango kugira ngo ahantu ukunda habe hafi yawe.",
    communityFallback: "Umuryango",
    createCommunity: "Kora umuryango",
    join: "Injira",
    leave: "Sohoka",
    members: "Abanyamuryango",

    createGroup: "Kora itsinda",
    groupBuilder: "Umwubatsi w’itsinda",
    groupName: "Izina ry’itsinda",
    categoryOptional: "Icyiciro (si ngombwa)",
    groupDescription: "Sobanura itsinda ryawe",
    creating: "Birimo gukora...",
    joined: "Winjiye",
    all: "Yose",
    posts: "Inyandiko",
    groupFallback: "Itsinda",
    noGroups: "Nta matsinda abonetse hano ubu.",
    noGroupsSub: "Gerageza gushakisha ukundi cyangwa ukore itsinda rya mbere.",

    privateChats: "Ibiganiro byihariye",
    chats: "Ibiganiro",
    focus: "Icyerekezo",
    open: "Bifunguye",
    idle: "Biratuje",
    peopleToMessage: "Abantu woherereza ubutumwa",
    peopleEmpty: "Tangira kuganira n’abantu uhereye kuri profile zabo.",
    conversations: "Ibiganiro",
    activeChats: "ibiganiro bikora",
    noConversations: "Nta biganiro birimo ubu.",
    openConversation: "Fungura ikiganiro",
    selectConversation: "Hitamo ikiganiro",
    selectConversationHelp:
      "Fungura chat ibumoso usome ubutumwa utangire kuganira.",
    openProfile: "Fungura umwirondoro",
    member: "umunyamuryango",
    noMessages: "Nta butumwa burimo ubu. Tangira ikiganiro.",
    message: "Ubutumwa",
    writeFirst: "Banza wandike ubutumwa.",
    selectFirst: "Banza uhitemo ikiganiro.",
    sending: "Birimo koherezwa...",
    send: "Ohereza",
    audioCall: "Guhamagara amajwi",
    videoCall: "Guhamagara video",
    endCall: "Soza guhamagara",
    callPreview: "Igerageza ryo guhamagara",
    callPermission: "Emerera mikoro/kamera kugira ngo igerageza ritangire.",
    incomingAudioCall: "Hari guhamagara amajwi",
    incomingVideoCall: "Hari guhamagara video",
    isCallingYou: "araguhamagara",
    accept: "Emera",
    decline: "Hakana",
    callDeclined: "Guhamagara byahakanywe",
    callStarted: "Guhamagara byatangiye",
    connecting: "Birimo kwihuza...",
    connected: "Byahujwe",
    online: "online",
    remoteVideo: "Video y’undi muntu",
    localPreview: "Igerageza ryawe",
    callEnded: "Guhamagara byarangiye",
    callFailed: "Guhamagara byanze",
    voiceRecord: "Ijwi",
    recording: "Birimo gufata amajwi...",
    stop: "Hagarika",
    voiceMessage: "Ubutumwa bw’ijwi",
    voiceUploadError: "Ntibyashobotse kohereza ubutumwa bw’ijwi.",
    recordingTip:
      "Vugira hafi ya mikoro. Reba mic ya browser cyangwa system niba ijwi ryawe ridafatwa.",
    micActive: "Mikoro iri gukora",

    creatorDashboard: "Dashibodi y’umuhanzi",
    tabs: "Amatab",
    creators: "Abahanzi",
    creator: "umuhanzi",
    creatorSpotlight: "Umuhanzi wihariye",
    trendingCreators: "Abahanzi bari kuvugwa",
    watchNow: "Reba ubu",
    upload: "Ohereza",
    uploadVideo: "Ohereza amashusho",
    publishVideo: "Tangaza amashusho",
    videoTitle: "Umutwe w’amashusho",
    videoDescription: "Ibisobanuro by’amashusho",
    noVideos: "Nta mashusho abonetse hano ubu.",
    noVideosSub: "Gerageza indi tab cyangwa wohereze video ya mbere.",
    views: "abarebye",

    quickDetails: "Kanda urebe ibisobanuro byihuse",
    savedStat: "Byabitswe",
    alertsStat: "Amamenyesha",
    groupsStat: "Amatsinda",
    openProfileTitle: "Fungura umwirondoro",
  },
} as const;

export type UiTranslationKey = keyof typeof uiTranslations.en;
export type UiTranslations = typeof uiTranslations.en;
